// flow-typed signature: 5ff65dc50f5d3a12b909f71ac4d222ee
// flow-typed version: <<STUB>>/bodymovin_v^4.4.28/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bodymovin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bodymovin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bodymovin/build/old_parser/bodymovin_parser' {
  declare module.exports: any;
}

declare module 'bodymovin/build/player/bodymovin_light' {
  declare module.exports: any;
}

declare module 'bodymovin/build/player/bodymovin_light.min' {
  declare module.exports: any;
}

declare module 'bodymovin/build/player/bodymovin' {
  declare module.exports: any;
}

declare module 'bodymovin/build/player/bodymovin.min' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/assets/player/bm' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/assets/player/standalone' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/js/animations/alert' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/js/animations/bm' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/js/animations/check' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/js/animations/folder' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/js/animations/gear' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/js/animations/radio' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/js/animations/rendering' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/js/animations/sucess' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/js/controllers/CompRenderController' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/js/controllers/CompSelectionController' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/js/controllers/compsSelection/CompsSelectionSettingsController' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/js/controllers/compsSelection/ExtraCompsSelectionSettingsController' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/js/controllers/InfoController' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/js/controllers/messageController' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/js/controllers/snapshotController' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/js/libs/bm' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/js/libs/bodymovin' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/js/libs/CSInterface' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/js/libs/jquery-2.0.2.min' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/js/libs/mustache' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/js/main' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/js/themeManager' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/js/utils/messageParser' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/js/utils/storage' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/compsManager' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/dataManager' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/downloadManager' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/elements/layerElement' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/escodegen' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/esprima' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/eventManager' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/hostscript' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/initializer' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/JSON' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/projectManager' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/renderManager' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/utils/bez' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/utils/cameraHelper' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/utils/effectsHelper' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/utils/expressionHelper' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/utils/generalUtils' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/utils/keyframeHelper' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/utils/layerStylesHelper' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/utils/markerHelper' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/utils/maskHelper' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/utils/ProjectParser' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/utils/PropertyFactory' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/utils/shapeHelper' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/utils/sourceHelper' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/utils/textAnimatorHelper' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/utils/textHelper' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/utils/textShapeHelper' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/utils/timeremapHelper' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/utils/transformation-matrix' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/utils/transformHelper' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/jsx/utils/XMPParser' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/node_modules/binpacking/js/demo' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/node_modules/binpacking/js/index' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/node_modules/binpacking/js/jquery' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/node_modules/binpacking/js/packer.growing' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/node_modules/binpacking/js/packer' {
  declare module.exports: any;
}

declare module 'bodymovin/extension/node_modules/binpacking/node-test' {
  declare module.exports: any;
}

declare module 'bodymovin/gulpfile' {
  declare module.exports: any;
}

declare module 'bodymovin/old_parser/AssetsManager' {
  declare module.exports: any;
}

declare module 'bodymovin/old_parser/AsyncManager' {
  declare module.exports: any;
}

declare module 'bodymovin/old_parser/CompConverter' {
  declare module.exports: any;
}

declare module 'bodymovin/old_parser/DOMAnimationManager' {
  declare module.exports: any;
}

declare module 'bodymovin/old_parser/EffectsParser' {
  declare module.exports: any;
}

declare module 'bodymovin/old_parser/EffectsStrokeParser' {
  declare module.exports: any;
}

declare module 'bodymovin/old_parser/extras' {
  declare module.exports: any;
}

declare module 'bodymovin/old_parser/global' {
  declare module.exports: any;
}

declare module 'bodymovin/old_parser/LayerConverter' {
  declare module.exports: any;
}

declare module 'bodymovin/old_parser/polyfills' {
  declare module.exports: any;
}

declare module 'bodymovin/old_parser/RQManager' {
  declare module.exports: any;
}

declare module 'bodymovin/old_parser/ShapesParser' {
  declare module.exports: any;
}

declare module 'bodymovin/old_parser/UI' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/3rd_party/BezierEaser' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/3rd_party/canvasPoly' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/3rd_party/seedrandom' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/3rd_party/sylvester' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/3rd_party/transformation-matrix' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/animation/AnimationItem' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/animation/AnimationManager' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/effects' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/effects/SliderEffect' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/effects/StrokeEffectManager' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/effects/TintEffect' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/BaseElement' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/BaseTextElement' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/canvasElements/CVBaseElement' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/canvasElements/CVCompElement' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/canvasElements/CVImageElement' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/canvasElements/CVMaskElement' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/canvasElements/CVShapeElement' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/canvasElements/CVShapeItemElement' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/canvasElements/CVSolidElement' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/canvasElements/CVTextElement' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/CompElement' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/htmlElements/HBaseElement' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/htmlElements/HCameraElement' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/htmlElements/HCompElement' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/htmlElements/HImageElement' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/htmlElements/HShapeElement' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/htmlElements/HSolidElement' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/htmlElements/HTextElement' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/ImageElement' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/PlaceHolderElement' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/ShapeElement' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/ShapeItemElement' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/SolidElement' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/svgElements/SVGBaseElement' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/svgElements/SVGEffects' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/svgElements/SVGTextElement' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/elements/TextElement' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/main' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/mask' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/module' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/players/BasicPlayer' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/players/PlayerManager' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/renderers/BaseRenderer' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/renderers/CanvasRenderer' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/renderers/HybridRenderer' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/renderers/SVGRenderer' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/utils/animationFramePolyFill' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/utils/bez' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/utils/common' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/utils/DataManager' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/utils/expressions/CompInterface' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/utils/expressions/EffectInterface' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/utils/expressions/ExpressionManager' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/utils/expressions/ExpressionPropertyDecorator' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/utils/expressions/Expressions' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/utils/expressions/LayerInterface' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/utils/expressions/ProjectInterface' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/utils/expressions/ShapeInterface' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/utils/expressions/TransformInterface' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/utils/featureSupport' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/utils/filters' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/utils/FontManager' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/utils/functionExtensions' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/utils/imagePreloader' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/utils/MatrixManager' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/utils/PropertyFactory' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/utils/shapes/MouseModifier' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/utils/shapes/RoundCornersModifier' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/utils/shapes/ShapeModifiers' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/utils/shapes/ShapeProperty' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/utils/shapes/TrimModifier' {
  declare module.exports: any;
}

declare module 'bodymovin/player/js/utils/text_helper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bodymovin/build/old_parser/bodymovin_parser.jsx' {
  declare module.exports: $Exports<'bodymovin/build/old_parser/bodymovin_parser'>;
}
declare module 'bodymovin/build/player/bodymovin_light.js' {
  declare module.exports: $Exports<'bodymovin/build/player/bodymovin_light'>;
}
declare module 'bodymovin/build/player/bodymovin_light.min.js' {
  declare module.exports: $Exports<'bodymovin/build/player/bodymovin_light.min'>;
}
declare module 'bodymovin/build/player/bodymovin.js' {
  declare module.exports: $Exports<'bodymovin/build/player/bodymovin'>;
}
declare module 'bodymovin/build/player/bodymovin.min.js' {
  declare module.exports: $Exports<'bodymovin/build/player/bodymovin.min'>;
}
declare module 'bodymovin/extension/assets/player/bm.js' {
  declare module.exports: $Exports<'bodymovin/extension/assets/player/bm'>;
}
declare module 'bodymovin/extension/assets/player/standalone.js' {
  declare module.exports: $Exports<'bodymovin/extension/assets/player/standalone'>;
}
declare module 'bodymovin/extension/js/animations/alert.js' {
  declare module.exports: $Exports<'bodymovin/extension/js/animations/alert'>;
}
declare module 'bodymovin/extension/js/animations/bm.js' {
  declare module.exports: $Exports<'bodymovin/extension/js/animations/bm'>;
}
declare module 'bodymovin/extension/js/animations/check.js' {
  declare module.exports: $Exports<'bodymovin/extension/js/animations/check'>;
}
declare module 'bodymovin/extension/js/animations/folder.js' {
  declare module.exports: $Exports<'bodymovin/extension/js/animations/folder'>;
}
declare module 'bodymovin/extension/js/animations/gear.js' {
  declare module.exports: $Exports<'bodymovin/extension/js/animations/gear'>;
}
declare module 'bodymovin/extension/js/animations/radio.js' {
  declare module.exports: $Exports<'bodymovin/extension/js/animations/radio'>;
}
declare module 'bodymovin/extension/js/animations/rendering.js' {
  declare module.exports: $Exports<'bodymovin/extension/js/animations/rendering'>;
}
declare module 'bodymovin/extension/js/animations/sucess.js' {
  declare module.exports: $Exports<'bodymovin/extension/js/animations/sucess'>;
}
declare module 'bodymovin/extension/js/controllers/CompRenderController.js' {
  declare module.exports: $Exports<'bodymovin/extension/js/controllers/CompRenderController'>;
}
declare module 'bodymovin/extension/js/controllers/CompSelectionController.js' {
  declare module.exports: $Exports<'bodymovin/extension/js/controllers/CompSelectionController'>;
}
declare module 'bodymovin/extension/js/controllers/compsSelection/CompsSelectionSettingsController.js' {
  declare module.exports: $Exports<'bodymovin/extension/js/controllers/compsSelection/CompsSelectionSettingsController'>;
}
declare module 'bodymovin/extension/js/controllers/compsSelection/ExtraCompsSelectionSettingsController.js' {
  declare module.exports: $Exports<'bodymovin/extension/js/controllers/compsSelection/ExtraCompsSelectionSettingsController'>;
}
declare module 'bodymovin/extension/js/controllers/InfoController.js' {
  declare module.exports: $Exports<'bodymovin/extension/js/controllers/InfoController'>;
}
declare module 'bodymovin/extension/js/controllers/messageController.js' {
  declare module.exports: $Exports<'bodymovin/extension/js/controllers/messageController'>;
}
declare module 'bodymovin/extension/js/controllers/snapshotController.js' {
  declare module.exports: $Exports<'bodymovin/extension/js/controllers/snapshotController'>;
}
declare module 'bodymovin/extension/js/libs/bm.js' {
  declare module.exports: $Exports<'bodymovin/extension/js/libs/bm'>;
}
declare module 'bodymovin/extension/js/libs/bodymovin.js' {
  declare module.exports: $Exports<'bodymovin/extension/js/libs/bodymovin'>;
}
declare module 'bodymovin/extension/js/libs/CSInterface.js' {
  declare module.exports: $Exports<'bodymovin/extension/js/libs/CSInterface'>;
}
declare module 'bodymovin/extension/js/libs/jquery-2.0.2.min.js' {
  declare module.exports: $Exports<'bodymovin/extension/js/libs/jquery-2.0.2.min'>;
}
declare module 'bodymovin/extension/js/libs/mustache.js' {
  declare module.exports: $Exports<'bodymovin/extension/js/libs/mustache'>;
}
declare module 'bodymovin/extension/js/main.js' {
  declare module.exports: $Exports<'bodymovin/extension/js/main'>;
}
declare module 'bodymovin/extension/js/themeManager.js' {
  declare module.exports: $Exports<'bodymovin/extension/js/themeManager'>;
}
declare module 'bodymovin/extension/js/utils/messageParser.js' {
  declare module.exports: $Exports<'bodymovin/extension/js/utils/messageParser'>;
}
declare module 'bodymovin/extension/js/utils/storage.js' {
  declare module.exports: $Exports<'bodymovin/extension/js/utils/storage'>;
}
declare module 'bodymovin/extension/jsx/compsManager.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/compsManager'>;
}
declare module 'bodymovin/extension/jsx/dataManager.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/dataManager'>;
}
declare module 'bodymovin/extension/jsx/downloadManager.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/downloadManager'>;
}
declare module 'bodymovin/extension/jsx/elements/layerElement.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/elements/layerElement'>;
}
declare module 'bodymovin/extension/jsx/escodegen.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/escodegen'>;
}
declare module 'bodymovin/extension/jsx/esprima.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/esprima'>;
}
declare module 'bodymovin/extension/jsx/eventManager.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/eventManager'>;
}
declare module 'bodymovin/extension/jsx/hostscript.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/hostscript'>;
}
declare module 'bodymovin/extension/jsx/initializer.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/initializer'>;
}
declare module 'bodymovin/extension/jsx/JSON.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/JSON'>;
}
declare module 'bodymovin/extension/jsx/projectManager.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/projectManager'>;
}
declare module 'bodymovin/extension/jsx/renderManager.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/renderManager'>;
}
declare module 'bodymovin/extension/jsx/utils/bez.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/utils/bez'>;
}
declare module 'bodymovin/extension/jsx/utils/cameraHelper.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/utils/cameraHelper'>;
}
declare module 'bodymovin/extension/jsx/utils/effectsHelper.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/utils/effectsHelper'>;
}
declare module 'bodymovin/extension/jsx/utils/expressionHelper.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/utils/expressionHelper'>;
}
declare module 'bodymovin/extension/jsx/utils/generalUtils.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/utils/generalUtils'>;
}
declare module 'bodymovin/extension/jsx/utils/keyframeHelper.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/utils/keyframeHelper'>;
}
declare module 'bodymovin/extension/jsx/utils/layerStylesHelper.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/utils/layerStylesHelper'>;
}
declare module 'bodymovin/extension/jsx/utils/markerHelper.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/utils/markerHelper'>;
}
declare module 'bodymovin/extension/jsx/utils/maskHelper.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/utils/maskHelper'>;
}
declare module 'bodymovin/extension/jsx/utils/ProjectParser.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/utils/ProjectParser'>;
}
declare module 'bodymovin/extension/jsx/utils/PropertyFactory.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/utils/PropertyFactory'>;
}
declare module 'bodymovin/extension/jsx/utils/shapeHelper.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/utils/shapeHelper'>;
}
declare module 'bodymovin/extension/jsx/utils/sourceHelper.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/utils/sourceHelper'>;
}
declare module 'bodymovin/extension/jsx/utils/textAnimatorHelper.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/utils/textAnimatorHelper'>;
}
declare module 'bodymovin/extension/jsx/utils/textHelper.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/utils/textHelper'>;
}
declare module 'bodymovin/extension/jsx/utils/textShapeHelper.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/utils/textShapeHelper'>;
}
declare module 'bodymovin/extension/jsx/utils/timeremapHelper.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/utils/timeremapHelper'>;
}
declare module 'bodymovin/extension/jsx/utils/transformation-matrix.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/utils/transformation-matrix'>;
}
declare module 'bodymovin/extension/jsx/utils/transformHelper.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/utils/transformHelper'>;
}
declare module 'bodymovin/extension/jsx/utils/XMPParser.jsx' {
  declare module.exports: $Exports<'bodymovin/extension/jsx/utils/XMPParser'>;
}
declare module 'bodymovin/extension/node_modules/binpacking/js/demo.js' {
  declare module.exports: $Exports<'bodymovin/extension/node_modules/binpacking/js/demo'>;
}
declare module 'bodymovin/extension/node_modules/binpacking/js/index.js' {
  declare module.exports: $Exports<'bodymovin/extension/node_modules/binpacking/js/index'>;
}
declare module 'bodymovin/extension/node_modules/binpacking/js/jquery.js' {
  declare module.exports: $Exports<'bodymovin/extension/node_modules/binpacking/js/jquery'>;
}
declare module 'bodymovin/extension/node_modules/binpacking/js/packer.growing.js' {
  declare module.exports: $Exports<'bodymovin/extension/node_modules/binpacking/js/packer.growing'>;
}
declare module 'bodymovin/extension/node_modules/binpacking/js/packer.js' {
  declare module.exports: $Exports<'bodymovin/extension/node_modules/binpacking/js/packer'>;
}
declare module 'bodymovin/extension/node_modules/binpacking/node-test.js' {
  declare module.exports: $Exports<'bodymovin/extension/node_modules/binpacking/node-test'>;
}
declare module 'bodymovin/gulpfile.js' {
  declare module.exports: $Exports<'bodymovin/gulpfile'>;
}
declare module 'bodymovin/old_parser/AssetsManager.js' {
  declare module.exports: $Exports<'bodymovin/old_parser/AssetsManager'>;
}
declare module 'bodymovin/old_parser/AsyncManager.js' {
  declare module.exports: $Exports<'bodymovin/old_parser/AsyncManager'>;
}
declare module 'bodymovin/old_parser/CompConverter.js' {
  declare module.exports: $Exports<'bodymovin/old_parser/CompConverter'>;
}
declare module 'bodymovin/old_parser/DOMAnimationManager.js' {
  declare module.exports: $Exports<'bodymovin/old_parser/DOMAnimationManager'>;
}
declare module 'bodymovin/old_parser/EffectsParser.js' {
  declare module.exports: $Exports<'bodymovin/old_parser/EffectsParser'>;
}
declare module 'bodymovin/old_parser/EffectsStrokeParser.js' {
  declare module.exports: $Exports<'bodymovin/old_parser/EffectsStrokeParser'>;
}
declare module 'bodymovin/old_parser/extras.js' {
  declare module.exports: $Exports<'bodymovin/old_parser/extras'>;
}
declare module 'bodymovin/old_parser/global.js' {
  declare module.exports: $Exports<'bodymovin/old_parser/global'>;
}
declare module 'bodymovin/old_parser/LayerConverter.js' {
  declare module.exports: $Exports<'bodymovin/old_parser/LayerConverter'>;
}
declare module 'bodymovin/old_parser/polyfills.js' {
  declare module.exports: $Exports<'bodymovin/old_parser/polyfills'>;
}
declare module 'bodymovin/old_parser/RQManager.js' {
  declare module.exports: $Exports<'bodymovin/old_parser/RQManager'>;
}
declare module 'bodymovin/old_parser/ShapesParser.js' {
  declare module.exports: $Exports<'bodymovin/old_parser/ShapesParser'>;
}
declare module 'bodymovin/old_parser/UI.js' {
  declare module.exports: $Exports<'bodymovin/old_parser/UI'>;
}
declare module 'bodymovin/player/js/3rd_party/BezierEaser.js' {
  declare module.exports: $Exports<'bodymovin/player/js/3rd_party/BezierEaser'>;
}
declare module 'bodymovin/player/js/3rd_party/canvasPoly.js' {
  declare module.exports: $Exports<'bodymovin/player/js/3rd_party/canvasPoly'>;
}
declare module 'bodymovin/player/js/3rd_party/seedrandom.js' {
  declare module.exports: $Exports<'bodymovin/player/js/3rd_party/seedrandom'>;
}
declare module 'bodymovin/player/js/3rd_party/sylvester.js' {
  declare module.exports: $Exports<'bodymovin/player/js/3rd_party/sylvester'>;
}
declare module 'bodymovin/player/js/3rd_party/transformation-matrix.js' {
  declare module.exports: $Exports<'bodymovin/player/js/3rd_party/transformation-matrix'>;
}
declare module 'bodymovin/player/js/animation/AnimationItem.js' {
  declare module.exports: $Exports<'bodymovin/player/js/animation/AnimationItem'>;
}
declare module 'bodymovin/player/js/animation/AnimationManager.js' {
  declare module.exports: $Exports<'bodymovin/player/js/animation/AnimationManager'>;
}
declare module 'bodymovin/player/js/effects.js' {
  declare module.exports: $Exports<'bodymovin/player/js/effects'>;
}
declare module 'bodymovin/player/js/effects/SliderEffect.js' {
  declare module.exports: $Exports<'bodymovin/player/js/effects/SliderEffect'>;
}
declare module 'bodymovin/player/js/effects/StrokeEffectManager.js' {
  declare module.exports: $Exports<'bodymovin/player/js/effects/StrokeEffectManager'>;
}
declare module 'bodymovin/player/js/effects/TintEffect.js' {
  declare module.exports: $Exports<'bodymovin/player/js/effects/TintEffect'>;
}
declare module 'bodymovin/player/js/elements/BaseElement.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/BaseElement'>;
}
declare module 'bodymovin/player/js/elements/BaseTextElement.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/BaseTextElement'>;
}
declare module 'bodymovin/player/js/elements/canvasElements/CVBaseElement.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/canvasElements/CVBaseElement'>;
}
declare module 'bodymovin/player/js/elements/canvasElements/CVCompElement.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/canvasElements/CVCompElement'>;
}
declare module 'bodymovin/player/js/elements/canvasElements/CVImageElement.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/canvasElements/CVImageElement'>;
}
declare module 'bodymovin/player/js/elements/canvasElements/CVMaskElement.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/canvasElements/CVMaskElement'>;
}
declare module 'bodymovin/player/js/elements/canvasElements/CVShapeElement.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/canvasElements/CVShapeElement'>;
}
declare module 'bodymovin/player/js/elements/canvasElements/CVShapeItemElement.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/canvasElements/CVShapeItemElement'>;
}
declare module 'bodymovin/player/js/elements/canvasElements/CVSolidElement.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/canvasElements/CVSolidElement'>;
}
declare module 'bodymovin/player/js/elements/canvasElements/CVTextElement.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/canvasElements/CVTextElement'>;
}
declare module 'bodymovin/player/js/elements/CompElement.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/CompElement'>;
}
declare module 'bodymovin/player/js/elements/htmlElements/HBaseElement.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/htmlElements/HBaseElement'>;
}
declare module 'bodymovin/player/js/elements/htmlElements/HCameraElement.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/htmlElements/HCameraElement'>;
}
declare module 'bodymovin/player/js/elements/htmlElements/HCompElement.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/htmlElements/HCompElement'>;
}
declare module 'bodymovin/player/js/elements/htmlElements/HImageElement.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/htmlElements/HImageElement'>;
}
declare module 'bodymovin/player/js/elements/htmlElements/HShapeElement.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/htmlElements/HShapeElement'>;
}
declare module 'bodymovin/player/js/elements/htmlElements/HSolidElement.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/htmlElements/HSolidElement'>;
}
declare module 'bodymovin/player/js/elements/htmlElements/HTextElement.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/htmlElements/HTextElement'>;
}
declare module 'bodymovin/player/js/elements/ImageElement.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/ImageElement'>;
}
declare module 'bodymovin/player/js/elements/PlaceHolderElement.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/PlaceHolderElement'>;
}
declare module 'bodymovin/player/js/elements/ShapeElement.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/ShapeElement'>;
}
declare module 'bodymovin/player/js/elements/ShapeItemElement.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/ShapeItemElement'>;
}
declare module 'bodymovin/player/js/elements/SolidElement.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/SolidElement'>;
}
declare module 'bodymovin/player/js/elements/svgElements/SVGBaseElement.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/svgElements/SVGBaseElement'>;
}
declare module 'bodymovin/player/js/elements/svgElements/SVGEffects.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/svgElements/SVGEffects'>;
}
declare module 'bodymovin/player/js/elements/svgElements/SVGTextElement.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/svgElements/SVGTextElement'>;
}
declare module 'bodymovin/player/js/elements/TextElement.js' {
  declare module.exports: $Exports<'bodymovin/player/js/elements/TextElement'>;
}
declare module 'bodymovin/player/js/main.js' {
  declare module.exports: $Exports<'bodymovin/player/js/main'>;
}
declare module 'bodymovin/player/js/mask.js' {
  declare module.exports: $Exports<'bodymovin/player/js/mask'>;
}
declare module 'bodymovin/player/js/module.js' {
  declare module.exports: $Exports<'bodymovin/player/js/module'>;
}
declare module 'bodymovin/player/js/players/BasicPlayer.js' {
  declare module.exports: $Exports<'bodymovin/player/js/players/BasicPlayer'>;
}
declare module 'bodymovin/player/js/players/PlayerManager.js' {
  declare module.exports: $Exports<'bodymovin/player/js/players/PlayerManager'>;
}
declare module 'bodymovin/player/js/renderers/BaseRenderer.js' {
  declare module.exports: $Exports<'bodymovin/player/js/renderers/BaseRenderer'>;
}
declare module 'bodymovin/player/js/renderers/CanvasRenderer.js' {
  declare module.exports: $Exports<'bodymovin/player/js/renderers/CanvasRenderer'>;
}
declare module 'bodymovin/player/js/renderers/HybridRenderer.js' {
  declare module.exports: $Exports<'bodymovin/player/js/renderers/HybridRenderer'>;
}
declare module 'bodymovin/player/js/renderers/SVGRenderer.js' {
  declare module.exports: $Exports<'bodymovin/player/js/renderers/SVGRenderer'>;
}
declare module 'bodymovin/player/js/utils/animationFramePolyFill.js' {
  declare module.exports: $Exports<'bodymovin/player/js/utils/animationFramePolyFill'>;
}
declare module 'bodymovin/player/js/utils/bez.js' {
  declare module.exports: $Exports<'bodymovin/player/js/utils/bez'>;
}
declare module 'bodymovin/player/js/utils/common.js' {
  declare module.exports: $Exports<'bodymovin/player/js/utils/common'>;
}
declare module 'bodymovin/player/js/utils/DataManager.js' {
  declare module.exports: $Exports<'bodymovin/player/js/utils/DataManager'>;
}
declare module 'bodymovin/player/js/utils/expressions/CompInterface.js' {
  declare module.exports: $Exports<'bodymovin/player/js/utils/expressions/CompInterface'>;
}
declare module 'bodymovin/player/js/utils/expressions/EffectInterface.js' {
  declare module.exports: $Exports<'bodymovin/player/js/utils/expressions/EffectInterface'>;
}
declare module 'bodymovin/player/js/utils/expressions/ExpressionManager.js' {
  declare module.exports: $Exports<'bodymovin/player/js/utils/expressions/ExpressionManager'>;
}
declare module 'bodymovin/player/js/utils/expressions/ExpressionPropertyDecorator.js' {
  declare module.exports: $Exports<'bodymovin/player/js/utils/expressions/ExpressionPropertyDecorator'>;
}
declare module 'bodymovin/player/js/utils/expressions/Expressions.js' {
  declare module.exports: $Exports<'bodymovin/player/js/utils/expressions/Expressions'>;
}
declare module 'bodymovin/player/js/utils/expressions/LayerInterface.js' {
  declare module.exports: $Exports<'bodymovin/player/js/utils/expressions/LayerInterface'>;
}
declare module 'bodymovin/player/js/utils/expressions/ProjectInterface.js' {
  declare module.exports: $Exports<'bodymovin/player/js/utils/expressions/ProjectInterface'>;
}
declare module 'bodymovin/player/js/utils/expressions/ShapeInterface.js' {
  declare module.exports: $Exports<'bodymovin/player/js/utils/expressions/ShapeInterface'>;
}
declare module 'bodymovin/player/js/utils/expressions/TransformInterface.js' {
  declare module.exports: $Exports<'bodymovin/player/js/utils/expressions/TransformInterface'>;
}
declare module 'bodymovin/player/js/utils/featureSupport.js' {
  declare module.exports: $Exports<'bodymovin/player/js/utils/featureSupport'>;
}
declare module 'bodymovin/player/js/utils/filters.js' {
  declare module.exports: $Exports<'bodymovin/player/js/utils/filters'>;
}
declare module 'bodymovin/player/js/utils/FontManager.js' {
  declare module.exports: $Exports<'bodymovin/player/js/utils/FontManager'>;
}
declare module 'bodymovin/player/js/utils/functionExtensions.js' {
  declare module.exports: $Exports<'bodymovin/player/js/utils/functionExtensions'>;
}
declare module 'bodymovin/player/js/utils/imagePreloader.js' {
  declare module.exports: $Exports<'bodymovin/player/js/utils/imagePreloader'>;
}
declare module 'bodymovin/player/js/utils/MatrixManager.js' {
  declare module.exports: $Exports<'bodymovin/player/js/utils/MatrixManager'>;
}
declare module 'bodymovin/player/js/utils/PropertyFactory.js' {
  declare module.exports: $Exports<'bodymovin/player/js/utils/PropertyFactory'>;
}
declare module 'bodymovin/player/js/utils/shapes/MouseModifier.js' {
  declare module.exports: $Exports<'bodymovin/player/js/utils/shapes/MouseModifier'>;
}
declare module 'bodymovin/player/js/utils/shapes/RoundCornersModifier.js' {
  declare module.exports: $Exports<'bodymovin/player/js/utils/shapes/RoundCornersModifier'>;
}
declare module 'bodymovin/player/js/utils/shapes/ShapeModifiers.js' {
  declare module.exports: $Exports<'bodymovin/player/js/utils/shapes/ShapeModifiers'>;
}
declare module 'bodymovin/player/js/utils/shapes/ShapeProperty.js' {
  declare module.exports: $Exports<'bodymovin/player/js/utils/shapes/ShapeProperty'>;
}
declare module 'bodymovin/player/js/utils/shapes/TrimModifier.js' {
  declare module.exports: $Exports<'bodymovin/player/js/utils/shapes/TrimModifier'>;
}
declare module 'bodymovin/player/js/utils/text_helper.js' {
  declare module.exports: $Exports<'bodymovin/player/js/utils/text_helper'>;
}
