// flow-typed signature: 92f23087645af8199b3caf2e092bf4d9
// flow-typed version: <<STUB>>/browserify-incremental_v^3.1.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browserify-incremental'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'browserify-incremental' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browserify-incremental/bin/cmd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browserify-incremental/bin/cmd.js' {
  declare module.exports: $Exports<'browserify-incremental/bin/cmd'>;
}
declare module 'browserify-incremental/index' {
  declare module.exports: $Exports<'browserify-incremental'>;
}
declare module 'browserify-incremental/index.js' {
  declare module.exports: $Exports<'browserify-incremental'>;
}
